config/routes.rb
Rails.application.routes.draw do
  # get '/:locale' => 'static_pages#home'
  scope "(:locale)", locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root   'static_pages#home'
    get    '/help',    to: 'static_pages#help'
    get    '/about',   to: 'static_pages#about'
    get    '/contact', to: 'static_pages#contact'
    get    '/signup',  to: 'users#new'
    # 登録に失敗した場合にも/usersにリダイレクトするのでなく、/signupにするために
    post   '/signup',  to: 'users#create'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    resources :users
    # ユーザーの有効化を行うリソース
    resources :account_activations, only: [:edit]
    # パスワード再設定を行うリソース(newとcreateがエントリー、editとupdateが再設定)
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :places do
        resources :photos, only: [:create, :destroy]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :places, dependent: :destroy

  # データベースに存在しないremember_token、activation_token、reset_token属性を用意

  attr_accessor :remember_token, :activation_token, :reset_token

  # 保存する前にメールアドレスを小文字化
  before_save   :downcase_email
  # ユーザーを作る前にだけ有効化ダイジェストを生成
  before_create :create_activation_digest

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # 連続した..を含んだメールアドレスを許容しない場合
  # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  # パスワードが空でも更新を可能にする。新規作成時に空だとhas_secure_passwordではねられる
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # この場合、selfはUserオブジェクトではなく、Userクラスを表す
  class << self
    # Returns the hash digest of the given string.
    # def User.digest(string)
    # この場合、selfはUserオブジェクトではなく、Userクラスを表す
    # def self.digest(string)
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
  
    # Returns a random token.
    # def User.new_token
    # この場合、selfはUserオブジェクトではなく、Userクラスを表す
    # def self.new_token
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    # 新しくトークンを生成
    self.remember_token = User.new_token
    # ハッシュ化し、データベースにバリデーションをスルーして保存
    # バリデーションをスルーしないとパスワードが必要になる
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  # attributeに何のトークンかを入れ、tokenにトークンそのものを入れて呼び出す
  def authenticated?(attribute, token)
    # digest変数に指定した種類のトークンのダイジェストを代入
    # sendメソッドは、オブジェクトにメッセージを送る
    # このコードでは、引数を使いメッセージの内容を動的に指定し、
    # データベースに保存された指定した種類のトークンのダイジェストを取得している
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    # トークンをダイジェスト化して、保存されたダイジェストと比較
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    # バリデーションをスルーしてremember_digestを空にする
    # バリデーションをスルーしないとパスワードが必要になる
    update_attribute(:remember_digest, nil)
  end

  # Activates an account
  def activate
    # update_attribute(:activated,    true)
    # update_attribute(:activated_at, Time.zone.now)
    # 以上の2行を1行で
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    # update_attribute(:reset_digest,  User.digest(reset_token))
    # update_attribute(:reset_sent_at, Time.zone.now)
    update_columns(reset_digest:  User.digest(reset_token),
                   reset_sent_at: Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    # パスワード再設定トークンの有効期限を2時間に設定
    reset_sent_at < 2.hours.ago
  end

  private

    # Converts email to all lower-case.
    def downcase_email
      # self.email = email.downcase
      email.downcase!
    end

    # Creates and assigns the activation token and digest
    # 有効化トークンとそのダイジェストを生成
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
                                        :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    # 有効なユーザーだけを取り出す
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    redirect_to root_url and return unless @user.activated?
    @places = @user.places.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # アカウント有効化メールを送る
      @user.send_activation_email
      flash[:info] = t(:please_check_your_email_to_activate_your_account)
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = t(:profile_updated)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:notice] = t(:user_deleted)
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirm an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_for(@user, options ||= {}) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <%# 管理者で自分以外のユーザーのときに限りdeleteリンクを表示 -%>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to t('.delete'), user, method: :delete,
                                  data: { confirm: t('.you_sure') } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, t('.edit_user')) %>
<% provide(:h1, t('.update_your_profile')) %>
<% provide(:button_text, t('.save_changes')) %>
<h1><%= yield(:h1) %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%#  Railsは@userが新規ユーザーか否かをnew_recordメソッドで見分け、編集用のフォームを生成 -%>
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <!-- 更新するときはGravatarのページを、元のウィンドウが操作できないようにして、
           新しいウィンドウで開く -->
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener"><%= t('.change') %></a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, t('.all_users')) %>
<h1><%= yield(:title) %></h1>

<%= will_paginate %>

<ul class="users">
  <%# users/showのテンプレートを繰り返し表示 -%>
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, t('.sign_up')) %>
<% provide(:button_text, t('.create_my_account')) %>
<h1><%= yield(:title) %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%# 登録に失敗した場合にも/usersにリダイレクトするのでなく、/signupにする -%>
    <%= render 'form', options: { url: signup_path } %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
      <h3><%= t('pluralize.place', count: 2) %> (<%= @user.places.count %>)</h3>

      <% if logged_in? and current_user?(@user) %>
        <%= link_to t('.new_place'), new_place_path, class: "btn btn-primary", "data-turbolinks" => "false" %>
      <% end %>

    <% if @user.places.any? %>
      <br>

      <%= will_paginate @places %>
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th><%= Place.human_attribute_name(:name) %></th>
            <th><%= Place.human_attribute_name(:mass) %></th>
            <th><%= Place.human_attribute_name(:collected_at) %></th>
            <% if logged_in? and current_user?(@user) %>
              <th colspan="3"></th>
            <% else %>
              <th></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <%= render @places %>
        </tbody>
      </table>
      <%= will_paginate @places %>
    <% end %>
  </div>
</div>