config/routes.rb
Rails.application.routes.draw do
  # get '/:locale' => 'static_pages#home'
  scope "(:locale)", locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root   'static_pages#home'
    get    '/help',    to: 'static_pages#help'
    get    '/about',   to: 'static_pages#about'
    get    '/contact', to: 'static_pages#contact'
    get    '/signup',  to: 'users#new'
    # 登録に失敗した場合にも/usersにリダイレクトするのでなく、/signupにするために
    post   '/signup',  to: 'users#create'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    resources :users
    # ユーザーの有効化を行うリソース
    resources :account_activations, only: [:edit]
    # パスワード再設定を行うリソース(newとcreateがエントリー、editとupdateが再設定)
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :places do
        resources :photos, only: [:create, :destroy]
    end
  end
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  default_scope -> { order(collected_at: :desc) }
  # uploaders/photos_uploader.rbと関連付け
  mount_uploaders :photos, PhotoUploader
  serialize :photos, JSON if (Rails.env.development? or Rails.env.test?)
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 140 }
  validates :mass, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :latitude, presence: true, numericality: { greater_than_or_equal_to: -90,  less_than_or_equal_to: 90 }
  validates :longitude, presence: true, numericality: { greater_than_or_equal_to: -180,  less_than_or_equal_to: 180 }
  validates :collected_at, presence: true

  validate  :photo_size

  private

    # Validates the size of an uploaded picture.
    def photo_size
      photos.each do |photo|
        if photo.size > 5.megabytes
          errors.add(:photos, I18n.t("activerecord.errors.messages.should_be_less_than_5MB"))
        end
      end
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :logged_in_user, except: [:index, :show]
  # 自分で投稿した場所だけ削除可能
  before_action :correct_user,   only: [:edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    respond_to do |format|
      format.html {
        @places = Place.paginate(page: params[:page])
      }
      format.json {
        @places = Place.all
      }
    end
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @place = Place.find(params[:id])
  end

  # GET /places/new
  def new
    @place = current_user.places.build(collected_at: Time.zone.now, latitude: 40.5092745, longitude: 141.4311736)
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  def create
    @place = current_user.places.build(place_params)
    if @place.save
      flash[:success] = t(:place_created)
      redirect_to @place
    else
      render :new
    end
  end

  # PATCH/PUT /places/1
  def update
    if @place.update(place_params_except_photos)
      flash[:success] = t(:place_updated)
      if place_params_only_photos[:photos].present?
        photos = @place.photos.any? ? @place.photos : []
        photos += place_params_only_photos[:photos]
        @place.photos = photos
        flash[:error] = "Failed uploading photos" unless @place.save
      end
      redirect_to @place
    else
      render :edit
    end
  end

  # DELETE /places/1
  def destroy
    @place.destroy
    flash[:success] = t(:place_deleted)
    # 削除を実行したページ(なければトップページ)にリダイレクト
    # redirect_to request.referrer || root_url
    # 上記と同じ
    redirect_back(fallback_location: root_url)
  end

  private

    def place_params
      params.require(:place).permit(:name, :description, :mass, :latitude, :longitude, :collected_at, {photos: []})
    end

    def place_params_except_photos
      params.require(:place).permit(:name, :description, :mass, :latitude, :longitude, :collected_at)
    end

    def place_params_only_photos
      params.require(:place).permit({photos: []})
    end

    def correct_user
      # 自分が投稿した場所からidを検索
      @place = current_user.places.find_by(id: params[:id])
      redirect_to root_url if @place.nil?
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :mass %>
    <%= f.text_field :mass, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :collected_at %>
    <div class="input-group date" id="datetimepicker">
      <%= f.text_field :collected_at, class: "form-control" %>
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
  </div>

  <script>
      $(function(){
          var options = { sideBySide: true, format: "YYYY/MM/DD HH:mm" };
          <% if I18n.locale %>
          options.locale = "<%= I18n.locale %>";
          <% end %>
          $("#datetimepicker").datetimepicker(options);
      });
  </script>

  <div class="field form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div id="map-position" style="width: 100%; height: 205px; border: 1px solid black;">
  </div>

  <div class="form-inline">
    <div class="field form-group">
      <%= f.label :latitude %>
      <%= f.text_field :latitude, placeholder: "40.5092745", class: "form-control" %>
    </div>
    <div class="field form-group">
      <%= f.label :longitude %>
      <%= f.text_field :longitude, placeholder: "141.4311736", class: "form-control" %>
    </div>
  </div>

  <script src="/google-map-position-edit.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC3igLoXPMmVDozoUpdWh2BVvoXR0alB0w&amp;callback=initMapPositionEdit" async defer></script>

  <% if @place.photos.present? %>
    <label><%= t('.current_photos') %></label>
    <div class="row">
      <% @place.photos.each_with_index do |photo, index| %>
        <div class="col-md-3" style="margin-bottom: 30px;">
          <%= image_tag photo.url, class: "img-responsive" %>
          <%= link_to t('.delete'), place_photo_path(@place, index), method: :delete, data: { confirm: t('.are_you_sure') } %>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="form-inline">
    <div class="field form-group">
      <%= f.label :photos, @place.photos.present? ? t('.add_more_photos') : t('.add_photos') %>
      <%= f.file_field :photos, multiple: true, onchange: "previewFiles()", class: "form-control", style: "border: none; box-shadow: none;" %>
    </div>
    <div id="images_preview"></div>
  </div>

  <script>
      function previewFiles() {
          var preview = document.querySelector('#images_preview');
          var files   = document.querySelector('input[type=file]').files;

          function readAndPreview(file) {
              // Make sure `file.name` matches our extensions criteria
              if (/\.(jpe?g|png|gif)$/i.test(file.name)) {
                  var reader = new FileReader();

                  reader.addEventListener("load", function () {
                      var image = new Image();
                      image.height = 100;
                      image.title = file.name;
                      image.src = this.result;
                      preview.appendChild(image);
                  }, false);
                  reader.readAsDataURL(file);
              }
          }

          if (files) {
              $("#images_preview").empty();
              [].forEach.call(files, readAndPreview);
          }
      }
  </script>

  <br>

  <div class="form-group">
    <%= submit_tag t('.post'), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/places/_place.html.erb
<tr>
  <td><%= place.name %></td>
  <td><%= place.mass %></td>
  <td><%= place.collected_at %></td>
  <td><%= link_to t('.show'), place, "data-turbolinks" => "false" %></td>
  <% if logged_in? and current_user?(place.user) %>
      <td><%= link_to t('.edit'), edit_place_path(place), "data-turbolinks" => "false" %></td>
      <td><%= link_to t('.destroy'), place, method: :delete, data: { confirm: t('.are_you_sure') } %></td>
  <% end %>
</tr>

app/views/places/edit.html.erb
<h1><%= t('.editing_place') %></h1>

<%= render 'form' %>

<hr>

<%= link_to t('.show'), @place, class: "btn btn-default", "data-turbolinks" => "false" %>
<%= link_to t('.back'), places_path, class: "btn btn-default" %>

app/views/places/index.html.erb
<h1><%= t('.listing_places') %></h1>

<% if logged_in? %>
  <%= link_to t('.new_place'), new_place_path, class: "btn btn-primary", "data-turbolinks" => "false" %>
<% end %>

<br>

<%= will_paginate @places %>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= User.model_name.human %></th>
      <th><%= Place.human_attribute_name(:name) %></th>
      <th><%= Place.human_attribute_name(:mass) %></th>
      <th><%= Place.human_attribute_name(:collected_at) %></th>
      <% if logged_in? %>
        <th colspan="3"></th>
      <% else %>
        <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><a href="<%= user_path(place.user) %>"><%= gravatar_for place.user, size: 50 %></a>
          <%= link_to place.user.name, place.user %></td>
        <td><%= place.name %></td>
        <td><%= place.mass %></td>
        <td><%= place.collected_at %></td>
        <td><%= link_to t('.show'), place, "data-turbolinks" => "false" %></td>
        <% if logged_in? %>
          <% if current_user?(place.user) %>
            <td><%= link_to t('.edit'), edit_place_path(place), "data-turbolinks" => "false" %></td>
            <td><%= link_to t('.destroy'), place, method: :delete, data: { confirm: t('.are_you_sure') } %></td>
          <% else %>
            <td></td>
            <td></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @places %>

app/views/places/new.html.erb
<h1><%= t('.new_place') %></h1>

<%= render 'form' %>

<%= link_to t('.back'), places_path, class: "btn btn-default" %>

app/views/places/show.html.erb
<table class="table table-striped">
  <tr>
    <th><%= User.model_name.human %></th>
    <td>
      <%= gravatar_for @place.user, size: 50 %>
      <%= @place.user.name %>
    </td>
  </tr>
  <tr>
    <th><%= Place.human_attribute_name('name') %></th>
    <td><%= @place.name %></td>
  </tr>
  <tr>
    <th>Map</th>
    <td><div id="map-position-show" style="width: 100%; height: 205px; border: 1px solid black;"></div></td>
  </tr>
  <script src="/google-map-position-show.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC3igLoXPMmVDozoUpdWh2BVvoXR0alB0w&amp;callback=initMapPositionShow" async defer></script>
  <tr>
    <th><%= Place.human_attribute_name('latitude') %></th>
    <td id="place_latitude"><%= @place.latitude %></td>
  </tr>
  <tr>
    <th><%= Place.human_attribute_name('longitude') %></th>
    <td id="place_longitude"><%= @place.longitude %></td>
  </tr>
  <tr>
    <th><%= Place.human_attribute_name('mass') %></th>
    <td><%= @place.mass %></td>
  </tr>
  <tr>
    <th><%= Place.human_attribute_name('collected_at') %></th>
    <td><%= @place.collected_at %></td>
  </tr>
  <tr>
    <th><%= Place.human_attribute_name('description') %></th>
    <td><%= @place.description %></td>
  </tr>
  <tr>
    <th><%= Place.human_attribute_name('photos') %></th>
    <td>
      <div class="row">
        <% @place.photos.each do |photo| %>
          <div class="col-md-3"><%= image_tag photo, class: "img-responsive" %></div>
        <% end %>
      </div>
    </td>
  </tr>
</table>

<% if logged_in? and current_user?(@place.user) %>
  <%= link_to t('.edit'), edit_place_path(@place), class: "btn btn-default", "data-turbolinks" => "false" %>
<% end %>
<%= link_to t('.back'), places_path, class: "btn btn-default" %>