config/routes.rb
Rails.application.routes.draw do
  # get '/:locale' => 'static_pages#home'
  scope "(:locale)", locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root   'static_pages#home'
    get    '/help',    to: 'static_pages#help'
    get    '/about',   to: 'static_pages#about'
    get    '/contact', to: 'static_pages#contact'
    get    '/signup',  to: 'users#new'
    # 登録に失敗した場合にも/usersにリダイレクトするのでなく、/signupにするために
    post   '/signup',  to: 'users#create'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    resources :users
    # ユーザーの有効化を行うリソース
    resources :account_activations, only: [:edit]
    # パスワード再設定を行うリソース(newとcreateがエントリー、editとupdateが再設定)
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :places do
        resources :photos, only: [:create, :destroy]
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom">
  <div class="container">
    <div class="md">
      <p class="navbar-text">
        <%= t('.international_environmental_education_program_on_micro_plastics_html') %>
      </p>
      <ul class="nav navbar-nav navbar-right md-ul">
        <li><%= link_to t('static_pages.about.title'), about_path %></li>
        <li><%= link_to t('static_pages.help.title'), help_path %></li>
        <li><%= link_to t('static_pages.contact.title'), contact_path %></li>
        <li><a href="#"><%= t('.news') %></a></li>
      </ul>
      <div class="row xs-row">
        <%= link_to t('static_pages.about.title'), about_path, class: "col-xs-6" %>
        <%= link_to t('static_pages.help.title'), help_path, class: "col-xs-6"  %>
        <%= link_to t('static_pages.contact.title'), contact_path, class: "col-xs-6"  %>
        <a href="#" class="col-xs-6"><%= t('.news') %></a>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Static navbar -->
<header class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand", "data-turbolinks" => "false" do %>
        <%= image_tag 'mp-mapping-logo.png', width: 20 %>
        <%= t('.app_name') %>
      <% end %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to t('.home'), root_path, "data-turbolinks" => "false" %></li>
        <li><%= link_to t('.places_list'), places_path %></li>
        <% if logged_in? %>
          <li><%= link_to t('.users_list'), users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t('.account') %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t('.profile'), current_user %></li>
              <li><%= link_to t('.settings'), edit_user_path(current_user) %></li>
              <li><a href="#">app settings</a></li>
              <li class="divider"></li>
              <li>
                <%= link_to t('.log_out'), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t('.log_in'), login_path %></li>
        <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t('.language') %> <b class="caret"></b>
            </a>
              <ul class="dropdown-menu">
                <% I18n.available_locales.each do |locale| %>
                  <li><a href="/<%= locale.to_s %>" data-turbolinks="false"><%= t('.' + locale.to_s) %></a></li>
                <% end %>
              </ul>
          </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container<%= @class_name%>" id="main">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= debug(params) if Rails.env.development? %>
    <%= render 'layouts/footer' %>
  </body>
</html>